print("Choose a place.")
place1=input()
print("Choose a noun.")
noun1=input()
print("Choose an action.")
action1=input()
print("Choose another noun")
noun2=input()
print("Give another action.")
action3=input()
print("Choose yet another noun.")
noun3=input()
print("Choose a place, again.")
place2=input()
print("Select an adjective.")
adjective1=input()
print("Pick a second action.")
action2=input()


print("PROCESSING DATA....")

print("There once lived a girl in a small town on the outskirts of a modern, everyday " + place1 + ".")
print("She lived on a farm with her father and a(n)" +  noun1 + ".")
print("She took her " + noun1 + " with her to the middle of town.")
print("The girl was " + adjective1 + ", which caused her to " + action1 + ", But despite that, " + noun1 + ", still stuck by her.")
print("On their way back home, she started to regret her previous actions... She was ashamed. But then they stumbled across a magical " + noun2 + ", that had the power to grant wishes.")
print("She decided it was worth a shot, so she asked for a wish. But her " + noun1 + " started to get a bad feeling about this so " + noun1 + " " + action2 + ".")
print("The girl " + action3 + " her " + noun1 + " and turned to the magical " + noun2 + " and made her wish.")
print("Girl: I wish everything would start over! So that none of this happened!")
print("With the wave of its " + noun3 + " the magical " + noun2 + "made her disappear.")
print("When she opened her eyes she found herself floating in " + place2 + ". Far away from any civilization, No one around her and all alone.")
